import type { Locale } from "./translations";
const en = {
  title: "Culture & Traditions", subtitle: "The customs, celebrations and everyday practices that bring Tamai together.",
  eyebrow: "THE WAYS WE BELONG", explore: "Explore the collection", progress: "Community documentation in progress",
  artTitle: "Many lives.\nA shared fabric.", artCaption: "A woven study of connection — a graphic, not an archival image.",
  introLabel: "LIVING CULTURE", introTitle: "In the occasions.\nIn the everyday.",
  introText: "Culture is more than a festival. It lives in family traditions, religious and social gatherings, food, local sports, seasonal routines and the way we welcome a guest. Ceremonies, community relationships and shared memories all belong in this collection.",
  introNote: "This is a space to document those experiences in Tamai, with the people who know them. Local accounts and photographs are still to be collected and reviewed.",
  themesLabel: "SIX THREADS OF COMMUNITY", themesTitle: "Ways of life, worth remembering.", themesText: "Starting points for future contributions, not a catalogue of confirmed local customs.",
  storyPending: "Community story to come", photoPending: "Photograph awaiting contribution",
  themes: [
    { title: "Festivals & Celebrations", text: "A place for memories of shared occasions: preparations, participation and the moments people choose to remember." },
    { title: "Family & Social Traditions", text: "Family accounts can help document how relationships, visits and shared responsibilities are experienced." },
    { title: "Religious & Community Life", text: "Space for respectful accounts of religious occasions, gatherings and the connections formed through community life." },
    { title: "Food & Hospitality", text: "Stories about preparing, sharing and serving food can preserve the personal meaning of hospitality." },
    { title: "Sports & Recreation", text: "A future record of play, competitions and leisure, told through participants’ memories and photographs." },
    { title: "Seasonal & Everyday Village Life", text: "Accounts of changing seasons and ordinary routines can give everyday experiences a place in the archive." },
  ],
  lifeLabel: "LIFE EVENTS & CEREMONIES", lifeTitle: "The moments\nwe gather around.", lifeText: "Community members can document how these traditions are practiced in Tamai. Personal accounts should leave room for differences between families, beliefs and generations.",
  lifeItems: ["Weddings", "Births", "Religious occasions", "Family gatherings", "Funerals & mourning", "Community milestones"], lifeNote: "Future accounts may describe an occasion, who took part and what it meant to them. Sensitive family memories and photographs should be shared with permission.",
  foodLabel: "FOOD & HOSPITALITY", foodTitle: "A meal. A welcome.\nA memory to share.", foodText: "Food and hospitality are part of how communities express care and connection. This collection invites the stories behind a meal: who prepared it, when it was shared and why it is remembered.", foodNote: "Topics for future documentation; no particular dish or custom is identified here as a Tamai tradition.",
  foodItems: ["Local dishes", "Festival foods", "Wedding foods", "Seasonal foods", "Traditional snacks", "Tea & hospitality customs"],
  sportsLabel: "SPORTS & RECREATION", sportsTitle: "Room for play,\nand the stories it leaves.", sportsText: "Future contributions can capture the people, places and friendships around recreation. A photograph, a programme or a participant’s account can help put a memory in context.",
  sportsItems: ["Village sports", "School competitions", "Traditional games", "Football & cricket", "Seasonal events", "Youth activities"], sportsNote: "Collection topics awaiting local accounts; these are not claims of established or unique Tamai traditions.",
  changeLabel: "ACROSS GENERATIONS", changeTitle: "Then & Now", changeText: "How might community life have changed? Future contributions can bring earlier memories and present-day accounts into conversation, with dates and sources where available.",
  then: "Then", now: "Now", thenPending: "Earlier account awaiting documentation", nowPending: "Present-day account awaiting documentation", changeNote: "An archival framework only. No historical comparisons have been published here.",
  changeTopics: ["Clothing & textile culture", "Weddings & celebrations", "Communication & entertainment", "Transport & village gatherings"],
  voicesLabel: "VOICES OF THE COMMUNITY", voicesTitle: "A place for your words.", voicesText: "Future quotations and short memories will appear with contributor permission and appropriate context. These spaces are empty for now.",
  voices: ["Elders", "Women", "Teachers", "Young people", "Weavers", "Business owners", "Long-time residents"], voicePending: "A memory yet to be shared",
  contributeLabel: "HELP BUILD THE COLLECTION", contributeTitle: "Share Tamai’s culture and traditions", contributeText: "Help preserve what matters to you. Share a memory, identify a photograph or suggest a correction through our contribution information page.", contributeButton: "How to contribute", contributeItems: ["Stories, old photos & wedding photos", "Festival, food & sports memories", "Cultural practices & family customs", "Corrections & helpful context"],
  galleryLabel: "THE CULTURE PHOTO ARCHIVE", galleryTitle: "Space for shared memories.", galleryText: "Reserved spaces for community photographs. No archival images have been added to this collection yet.", galleryItems: ["Celebrations", "Family events", "Food", "Sports", "Village gatherings", "Seasonal life"],
};
const bn: typeof en = {
  title: "সংস্কৃতি ও ঐতিহ্য", subtitle: "যে রীতি, উৎসব ও দৈনন্দিন জীবনধারা তামাইয়ের মানুষকে একসূত্রে বাঁধে।",
  eyebrow: "আমাদের একসঙ্গে থাকার গল্প", explore: "সংগ্রহটি দেখুন", progress: "বাসিন্দাদের অংশগ্রহণে নথিভুক্তির কাজ চলছে",
  artTitle: "নানা জীবন।\nএকই বুনন।", artCaption: "পারস্পরিক সম্পর্কের বুনন থেকে অনুপ্রাণিত নকশা — আর্কাইভের ছবি নয়।",
  introLabel: "জীবন্ত সংস্কৃতি", introTitle: "বিশেষ আয়োজনে।\nপ্রতিদিনের জীবনে।",
  introText: "সংস্কৃতি শুধু উৎসবে সীমাবদ্ধ নয়। পারিবারিক রীতি, ধর্মীয় ও সামাজিক সমাবেশ, খাবার, স্থানীয় খেলাধুলা, ঋতুভিত্তিক অভ্যাস ও অতিথিকে স্বাগত জানানোর মধ্যেও তার প্রকাশ। আচার-অনুষ্ঠান, পারস্পরিক সম্পর্ক ও একসঙ্গে কাটানো সময়ের স্মৃতিও এই সংগ্রহের অংশ।",
  introNote: "যাঁরা এসব অভিজ্ঞতার অংশ, তাঁদের সঙ্গে নিয়ে তামাইয়ের জীবন নথিভুক্ত করার এই উদ্যোগ। স্থানীয় বয়ান ও ছবি সংগ্রহ এবং যাচাই করা এখনও বাকি।",
  themesLabel: "সমাজজীবনের ছয়টি সুতো", themesTitle: "জীবনযাপনের গল্প, মনে রাখার মতো।", themesText: "ভবিষ্যৎ অবদানের বিষয়সূচি; যাচাই করা স্থানীয় রীতির তালিকা নয়।",
  storyPending: "বাসিন্দাদের গল্পের অপেক্ষায়", photoPending: "ছবি সংগ্রহের অপেক্ষায়",
  themes: [
    { title: "উৎসব ও উদযাপন", text: "সম্মিলিত আয়োজনের প্রস্তুতি, অংশগ্রহণ ও মনে রাখার মতো মুহূর্তের স্মৃতি তুলে ধরার জায়গা।" },
    { title: "পারিবারিক ও সামাজিক রীতি", text: "পরিবারের বয়ানে উঠে আসতে পারে সম্পর্ক, আত্মীয়স্বজনের সঙ্গে দেখা করা ও ভাগ করে নেওয়া দায়িত্বের অভিজ্ঞতা।" },
    { title: "ধর্মীয় ও সামাজিক জীবন", text: "ধর্মীয় উপলক্ষ, সমাবেশ ও সমাজজীবনের মধ্য দিয়ে গড়ে ওঠা সম্পর্কের কথা সম্মানের সঙ্গে নথিভুক্ত করার স্থান।" },
    { title: "খাবার ও আতিথেয়তা", text: "রান্না করা, খাবার ভাগ করে নেওয়া ও পরিবেশনের গল্পে ধরা থাকতে পারে আতিথেয়তার ব্যক্তিগত অর্থ।" },
    { title: "খেলাধুলা ও বিনোদন", text: "অংশগ্রহণকারীদের স্মৃতি ও ছবিতে খেলাধুলা, প্রতিযোগিতা এবং অবসর কাটানোর ভবিষ্যৎ সংগ্রহ।" },
    { title: "ঋতুভিত্তিক ও দৈনন্দিন গ্রামীণ জীবন", text: "বদলে যাওয়া ঋতু ও সাধারণ দিনের বয়ান দৈনন্দিন অভিজ্ঞতাকেও আর্কাইভে জায়গা করে দিতে পারে।" },
  ],
  lifeLabel: "জীবনের উপলক্ষ ও আচার-অনুষ্ঠান", lifeTitle: "যে মুহূর্তগুলো\nআমাদের একত্র করে।", lifeText: "তামাইয়ে এসব রীতি কীভাবে পালিত হয়, বাসিন্দারা তা নথিভুক্ত করতে পারেন। ব্যক্তিগত বয়ানে পরিবার, বিশ্বাস ও প্রজন্মভেদে ভিন্নতার জায়গাও থাকা প্রয়োজন।",
  lifeItems: ["বিয়ে", "জন্ম", "ধর্মীয় উপলক্ষ", "পারিবারিক মিলন", "মৃত্যু ও শোক পালন", "সমাজজীবনের উল্লেখযোগ্য মুহূর্ত"], lifeNote: "ভবিষ্যৎ বয়ানে আয়োজন, অংশগ্রহণকারী ও ব্যক্তিগত অনুভূতির কথা থাকতে পারে। সংবেদনশীল পারিবারিক স্মৃতি ও ছবি অনুমতি নিয়ে শেয়ার করা উচিত।",
  foodLabel: "খাবার ও আতিথেয়তা", foodTitle: "একবেলার খাবার।\nস্বাগত জানানোর স্মৃতি।", foodText: "খাবার ও আতিথেয়তার মধ্য দিয়ে যত্ন ও সম্পর্কের প্রকাশ ঘটে। একটি খাবারের পেছনের গল্প জানতে চাই: কে তৈরি করেছিলেন, কখন একসঙ্গে খাওয়া হয়েছিল, কেন তা মনে আছে।", foodNote: "এগুলো ভবিষ্যৎ নথিভুক্তির বিষয়। কোনো বিশেষ পদ বা রীতিকে এখানে তামাইয়ের ঐতিহ্য হিসেবে চিহ্নিত করা হয়নি।",
  foodItems: ["স্থানীয় খাবার", "উৎসবের খাবার", "বিয়ের খাবার", "মৌসুমি খাবার", "ঐতিহ্যবাহী নাশতা", "চা ও আপ্যায়নের রীতি"],
  sportsLabel: "খেলাধুলা ও বিনোদন", sportsTitle: "খেলার আনন্দ,\nথেকে যাওয়া গল্প।", sportsText: "বিনোদনকে ঘিরে মানুষ, স্থান ও বন্ধুত্বের কথা উঠে আসতে পারে ভবিষ্যৎ অবদানে। একটি ছবি, আয়োজনের বিবরণ বা অংশগ্রহণকারীর বয়ান স্মৃতির প্রেক্ষাপট বুঝতে সাহায্য করতে পারে।",
  sportsItems: ["গ্রামের খেলাধুলা", "বিদ্যালয়ের প্রতিযোগিতা", "ঐতিহ্যবাহী খেলা", "ফুটবল ও ক্রিকেট", "মৌসুমি আয়োজন", "তরুণদের কর্মকাণ্ড"], sportsNote: "স্থানীয় বয়ানের অপেক্ষায় থাকা সংগ্রহের বিষয়; তামাইয়ের প্রতিষ্ঠিত বা অনন্য রীতির দাবি নয়।",
  changeLabel: "প্রজন্ম থেকে প্রজন্মে", changeTitle: "তখন ও এখন", changeText: "সমাজজীবনে কী কী পরিবর্তন এসে থাকতে পারে? ভবিষ্যৎ অবদানে পুরোনো স্মৃতির পাশে বর্তমানের বয়ান রাখা যাবে, সম্ভব হলে সময় ও তথ্যসূত্রসহ।",
  then: "তখন", now: "এখন", thenPending: "আগের দিনের বয়ান নথিভুক্তির অপেক্ষায়", nowPending: "বর্তমানের বয়ান নথিভুক্তির অপেক্ষায়", changeNote: "এটি কেবল আর্কাইভের কাঠামো। এখানে কোনো ঐতিহাসিক তুলনা প্রকাশিত হয়নি।",
  changeTopics: ["পোশাক ও বস্ত্রসংস্কৃতি", "বিয়ে ও উদযাপন", "যোগাযোগ ও বিনোদন", "যাতায়াত ও গ্রামের সমাবেশ"],
  voicesLabel: "বাসিন্দাদের কণ্ঠে", voicesTitle: "আপনার কথার জন্য একটি জায়গা।", voicesText: "ভবিষ্যতে অবদানকারীর অনুমতি ও প্রয়োজনীয় প্রেক্ষাপটসহ উদ্ধৃতি এবং ছোট স্মৃতি প্রকাশিত হবে। আপাতত এই জায়গাগুলো খালি আছে।",
  voices: ["প্রবীণেরা", "নারীরা", "শিক্ষকেরা", "তরুণেরা", "তাঁতিরা", "ব্যবসায়ীরা", "দীর্ঘদিনের বাসিন্দারা"], voicePending: "একটি স্মৃতি শোনার অপেক্ষায়",
  contributeLabel: "সংগ্রহ গড়তে পাশে থাকুন", contributeTitle: "তামাইয়ের সংস্কৃতি ও ঐতিহ্যের গল্প শেয়ার করুন", contributeText: "আপনার কাছে মূল্যবান স্মৃতি সংরক্ষণে সাহায্য করুন। অবদান রাখার তথ্যপাতার মাধ্যমে স্মৃতি জানান, ছবি শনাক্ত করুন বা সংশোধন প্রস্তাব করুন।", contributeButton: "যেভাবে অবদান রাখবেন", contributeItems: ["গল্প, পুরোনো ছবি ও বিয়ের ছবি", "উৎসব, খাবার ও খেলাধুলার স্মৃতি", "সাংস্কৃতিক চর্চা ও পারিবারিক রীতি", "সংশোধন ও প্রয়োজনীয় প্রেক্ষাপট"],
  galleryLabel: "সংস্কৃতির ছবি সংগ্রহ", galleryTitle: "একসঙ্গে কাটানো সময়ের জন্য।", galleryText: "বাসিন্দাদের ছবির জন্য সংরক্ষিত জায়গা। এই সংগ্রহে এখনও কোনো আর্কাইভের ছবি যুক্ত হয়নি।", galleryItems: ["উদযাপন", "পারিবারিক অনুষ্ঠান", "খাবার", "খেলাধুলা", "গ্রামের সমাবেশ", "ঋতুর জীবন"],
};
export const cultureTranslations = { en, bn } satisfies Record<Locale, typeof en>;