import type { Locale } from "./translations";

export type HistoryStatus = "documented" | "oral" | "memory" | "review";
export const historyStatuses: HistoryStatus[] = ["documented", "oral", "memory", "review"];
export const historyPhases = ["settlement", "institutions", "weaving", "liberation", "powerlooms", "modern"] as const;
export type HistoryPhase = typeof historyPhases[number];
// These are research themes, not sourced historical entries. Change a status
// only when actual source material and its provenance have been reviewed.
export const historyTimeline: ReadonlyArray<{ id: HistoryPhase; status: HistoryStatus }> =
  historyPhases.map(id => ({ id, status: "review" }));

const en = {
  title: "History of Tamai",
  subtitle: "A village remembered through records, stories and generations.",
  eyebrow: "OUR ROOTS, CAREFULLY REMEMBERED",
  lead: "A place for Tamai’s written records, spoken histories and shared memories — with room to ask questions, compare accounts and keep learning.",
  explore: "Explore the history",
  heroArtTitle: "Keeping our\npast in view.",
  heroArtLabel: "THE COMMUNITY ARCHIVE",
  heroArtCaption: "An illustrative archive study. Original records are yet to be added.",
  contents: "IN THIS CHAPTER",
  chapters: ["Reading our history", "Historical timeline", "The Liberation War", "Origin & settlement", "Institutions", "Voices of Tamai", "Sources & evidence"],
  introLabel: "HISTORY IS HELD IN MANY HANDS",
  introTitle: "Written in records.\nRemembered by people.",
  introLead: "Tamai’s history belongs in both the records that survive and the memories people carry.",
  introText: "Village histories are often kept by families, elders, institutions and community storytelling. This archive aims to bring those materials together, record where they came from, compare accounts and preserve them over time.",
  introNote: "The historical sections below are a framework for future documentation. No local historical records or individual testimonies have been published here yet.",
  legendTitle: "How to read this archive",
  legendNote: "These labels describe the source or review state of an entry. They are not interchangeable, and a recollection is not automatically a verified historical fact.",
  statuses: {
    documented: { label: "Documented History", short: "Documented", description: "An account supported by identified records, with its sources and context reviewed." },
    oral: { label: "Oral History", short: "Oral", description: "A spoken account, preserved with the narrator’s context and permission. Its claims may still need corroboration." },
    memory: { label: "Community Memory", short: "Memory", description: "A shared or personal recollection, presented as remembered rather than independently verified." },
    review: { label: "Under Review", short: "Under Review", description: "A research question, incomplete account or material awaiting source checks and comparison." },
  },
  timelineLabel: "A HISTORY STILL TAKING SHAPE",
  timelineTitle: "Threads of the\nvillage story.",
  timelineText: "An expandable outline of themes to investigate. These phases are not a dated chronology and may overlap.",
  timelineNote: "All six themes currently remain under review. A theme is not evidence that a particular event or date has been established.",
  timeline: {
    settlement: { title: "Early settlement and village formation", text: "How did the village take shape? Family accounts, land records and other local material may help document settlement over generations.", material: "To seek: settlement accounts and available records." },
    institutions: { title: "Growth of community institutions", text: "Schools, places of worship, markets and shared facilities can help trace village development. Their individual histories and dates await verification.", material: "To seek: institutional records and photographs." },
    weaving: { title: "Development of weaving and textile identity", text: "Weaving is part of Tamai’s identity. The course of its development is a subject for research through family histories, workshop material and local accounts.", material: "To seek: craft memories and workshop records." },
    liberation: { title: "Liberation War period", text: "A place for carefully reviewed records and recollections connected with the 1971 Liberation War. No specific local event is asserted in this outline.", material: "To seek: documents and contextualized testimony." },
    powerlooms: { title: "Expansion of power loom and local business", text: "Tamai has a present-day power loom and lungi business. When and how individual businesses developed should be established through sources, not assumptions.", material: "To seek: business records and first-hand accounts." },
    modern: { title: "Modern Tamai", text: "Changes in everyday life, local places and community activity can be documented through photographs, records and the experiences of residents.", material: "To seek: contemporary records and community photographs." },
  },
  warLabel: "REMEMBERING THE LIBERATION WAR",
  warTitle: "A place for testimony.\nA responsibility to remember.",
  warText: "Memories connected to the 1971 Liberation War are part of Tamai and the wider Belkuchi–Sirajganj area. This section is reserved for preserving records, local testimonies, names, photographs and memories with care.",
  warNote: "Local names, sites and event details will be published only with clear sourcing and review. The spaces below identify future collection areas, not accounts already held by this archive.",
  warCollections: ["Eyewitness accounts", "Freedom fighter stories", "Old photographs", "Local sites", "Documents"],
  collectionPending: "Awaiting source material",
  originLabel: "A PLACE SHAPED OVER GENERATIONS",
  originTitle: "Origins, settlement\nand a changing landscape.",
  originText: "Understanding how a village develops means asking about the families who settled there, the names of neighbourhoods, and changes in land, roads, waterways and community life. In Tamai, these are questions to explore through local material.",
  originThemes: ["Family settlement patterns", "Neighbourhoods & local areas", "Land, roads & waterways", "Changes in community life"],
  nameTitle: "Origin of the name Tamai",
  researchStatus: "Community research in progress",
  nameText: "The origin of the name has not been verified in this archive. Different local accounts can be collected, attributed and compared with available records before a historical interpretation is offered.",
  institutionsLabel: "PLACES THAT KEEP A RECORD",
  institutionsTitle: "Institutions through time.",
  institutionsText: "Registers, meeting notes, photographs and other institutional records can offer clues to how village life developed. Specific names and founding dates will be added when supported by sources.",
  institutions: ["Schools", "Madrasas", "Mosques", "Markets", "Social organizations", "Public & community facilities"],
  institutionLink: "Explore the institutions directory",
  institutionNote: "Verified institution records will be added through community contributions and source review.",
  voicesLabel: "THE LIVING ARCHIVE",
  voicesTitle: "Voices of Tamai",
  voicesText: "Elders and long-time residents can help preserve the texture of village life: what people did, how places changed and what families remember.",
  voicesTopics: ["Personal memories", "Family stories", "Old customs", "Changes in village life", "Textile memories", "1971 recollections", "Institution histories"],
  principleLabel: "OUR APPROACH TO ORAL HISTORY",
  principle: "A memory deserves to be heard.\nIts context deserves to be kept.",
  principleText: "Oral history has value in its own right. We will identify who is speaking, when an account was shared and what is remembered directly or passed down. A testimony will remain identified as testimony, even when it differs from a written record.",
  voicesNote: "No interview or personal quotation is presented here yet. Future accounts will be shared with permission.",
  sourcesLabel: "THE MATERIAL BEHIND THE STORY",
  sourcesTitle: "Sources & evidence.",
  sourcesText: "A history becomes easier to understand when we can see its sources. These are the kinds of material the archive aims to preserve.",
  sources: [
    { title: "Written records", description: "The record’s author, purpose and context, where known." },
    { title: "Old photographs", description: "Who shared the image, what it shows and when it may have been taken." },
    { title: "School documents", description: "Registers, reports and other material retained by schools or families." },
    { title: "Mosque & madrasa records", description: "Institutional documents with their origin and context identified." },
    { title: "Land or administrative documents", description: "Relevant records, with their source and historical context checked." },
    { title: "Newspaper clippings", description: "The publication, article and date preserved alongside the clipping." },
    { title: "Family collections", description: "Letters, papers and photographs with the family’s account of their origin." },
    { title: "Oral testimony", description: "The narrator, recording context and any limits of recollection." },
    { title: "Community photographs", description: "Contemporary images with captions, source details and permission." },
  ],
  sourceNote: "A source type is not a verification status. Written material can be incomplete, and oral accounts can offer valuable evidence. Entries will retain their provenance, review state and any unresolved differences.",
  sourceLegend: "ARCHIVE LABELS",
  contributeLabel: "HELP COMPLETE THE RECORD",
  contributeTitle: "What you have kept\nmay help us remember.",
  contributeText: "Old photographs, family papers and carefully recalled details can help build a fuller history. Corrections are welcome, and names and dates should come with sources that can be checked.",
  contributeItems: ["Old photographs", "Family documents", "Historical memories", "Institution records", "Corrections", "Names & dates with supporting sources"],
  contributeButton: "Help preserve Tamai’s history",
  contributeNote: "Contributions are not open yet. Keep source details and permission to share with your material.",
};

const bn: typeof en = {
  title: "তামাইয়ের ইতিহাস",
  subtitle: "নথি, স্মৃতি ও প্রজন্মের গল্পে সংরক্ষিত একটি গ্রামের ইতিহাস।",
  eyebrow: "যত্নে ফিরে দেখা আমাদের শিকড়",
  lead: "তামাইয়ের লিখিত নথি, মুখে বলা ইতিহাস ও সবার স্মৃতির একটি ঠিকানা—যেখানে প্রশ্ন করা, বিবরণ মেলানো ও আরও জানার সুযোগ থাকবে।",
  explore: "ইতিহাসের পথে দেখুন",
  heroArtTitle: "অতীতকে রাখি\nআমাদের কাছে।",
  heroArtLabel: "কমিউনিটি আর্কাইভ",
  heroArtCaption: "আর্কাইভের প্রতীকী চিত্র। মূল নথি এখনো যুক্ত করা হয়নি।",
  contents: "এই অধ্যায়ে",
  chapters: ["ইতিহাস পাঠের পরিচিতি", "ইতিহাসের রূপরেখা", "মুক্তিযুদ্ধ", "উৎপত্তি ও বসতি", "প্রতিষ্ঠান", "মানুষের স্মৃতি", "তথ্যসূত্র ও প্রমাণ"],
  introLabel: "অনেকের কাছে রাখা এক ইতিহাস",
  introTitle: "নথিতে লেখা।\nমানুষের মনে রাখা।",
  introLead: "টিকে থাকা নথি আর মানুষের বহন করা স্মৃতি—দুই জায়গাতেই তামাইয়ের ইতিহাসের ঠিকানা।",
  introText: "গ্রামের ইতিহাসের অনেকটাই থাকে পরিবার, প্রবীণ মানুষ, প্রতিষ্ঠান এবং মুখে মুখে বলা গল্পে। এই আর্কাইভের লক্ষ্য সেসব উপকরণ একত্র করা, উৎস লেখা, বিবরণ মিলিয়ে দেখা এবং সময়ের সঙ্গে সংরক্ষণ করা।",
  introNote: "নিচের ঐতিহাসিক অংশগুলো ভবিষ্যতে তথ্য সংরক্ষণের একটি কাঠামো। এখানে এখনো স্থানীয় ঐতিহাসিক নথি বা ব্যক্তিগত সাক্ষ্য প্রকাশ করা হয়নি।",
  legendTitle: "এই আর্কাইভ যেভাবে পড়বেন",
  legendNote: "লেবেলগুলো কোনো বিবরণের উৎস বা যাচাইয়ের অবস্থা বোঝায়। এগুলো এক বিষয় নয়, আর কোনো স্মৃতি নিজে থেকেই যাচাইকৃত ঐতিহাসিক তথ্য হয়ে যায় না।",
  statuses: {
    documented: { label: "নথিভিত্তিক ইতিহাস", short: "নথিভিত্তিক", description: "চিহ্নিত নথির সমর্থন রয়েছে এবং উৎস ও প্রেক্ষাপট পর্যালোচনা করা হয়েছে—এমন বিবরণ।" },
    oral: { label: "মৌখিক ইতিহাস", short: "মৌখিক", description: "বক্তার প্রেক্ষাপট ও অনুমতিসহ সংরক্ষিত মুখে বলা বিবরণ। এর দাবিগুলোর জন্য আরও সমর্থন প্রয়োজন হতে পারে।" },
    memory: { label: "কমিউনিটির স্মৃতি", short: "স্মৃতি", description: "ব্যক্তিগত বা সবার মনে থাকা কথা, যা স্বাধীনভাবে যাচাইকৃত তথ্যের বদলে স্মৃতি হিসেবেই উপস্থাপিত।" },
    review: { label: "যাচাইাধীন", short: "যাচাইাধীন", description: "গবেষণার প্রশ্ন, অসম্পূর্ণ বিবরণ অথবা উৎস যাচাই ও তুলনার অপেক্ষায় থাকা উপকরণ।" },
  },
  timelineLabel: "যে ইতিহাস এখনো গড়ে উঠছে",
  timelineTitle: "গ্রামের গল্পের\nনানা সূত্র।",
  timelineText: "গবেষণার বিষয়গুলোর একটি প্রসারণযোগ্য রূপরেখা। এটি সাল অনুযায়ী সাজানো কালপঞ্জি নয়; বিষয়গুলোর সময়কাল পরস্পরের সঙ্গে মিলে যেতে পারে।",
  timelineNote: "ছয়টি বিষয়ই বর্তমানে যাচাইাধীন। কোনো বিষয় এখানে থাকার অর্থ এই নয় যে একটি নির্দিষ্ট ঘটনা বা সাল প্রমাণিত হয়েছে।",
  timeline: {
    settlement: { title: "প্রথম বসতি ও গ্রাম গড়ে ওঠা", text: "গ্রাম কীভাবে গড়ে উঠেছিল? পারিবারিক বিবরণ, জমির নথি ও অন্যান্য স্থানীয় উপকরণ থেকে প্রজন্ম ধরে বসতি গড়ার কথা জানা যেতে পারে।", material: "যা খোঁজা হবে: বসতির বিবরণ ও প্রাপ্ত নথি।" },
    institutions: { title: "সামাজিক প্রতিষ্ঠানগুলোর বিকাশ", text: "শিক্ষাপ্রতিষ্ঠান, উপাসনালয়, বাজার ও সবার ব্যবহার্য স্থানের মাধ্যমে গ্রামের বিকাশ বোঝা যেতে পারে। এগুলোর পৃথক ইতিহাস ও সাল এখনো যাচাই করা বাকি।", material: "যা খোঁজা হবে: প্রতিষ্ঠানের নথি ও ছবি।" },
    weaving: { title: "তাঁত ও বস্ত্রশিল্পের পরিচয় গড়ে ওঠা", text: "তাঁতশিল্প তামাইয়ের পরিচয়ের অংশ। এর বিকাশের ধারা খুঁজতে পারিবারিক ইতিহাস, কর্মশালার উপকরণ ও স্থানীয় বিবরণ নিয়ে গবেষণা দরকার।", material: "যা খোঁজা হবে: শিল্পের স্মৃতি ও কর্মশালার নথি।" },
    liberation: { title: "মুক্তিযুদ্ধের সময়কাল", text: "১৯৭১ সালের মুক্তিযুদ্ধের সঙ্গে সম্পর্কিত যত্নে পর্যালোচিত নথি ও স্মৃতির জন্য একটি স্থান। এই রূপরেখায় কোনো নির্দিষ্ট স্থানীয় ঘটনার দাবি করা হচ্ছে না।", material: "যা খোঁজা হবে: নথি ও প্রেক্ষাপটসহ সাক্ষ্য।" },
    powerlooms: { title: "পাওয়ার লুম ও স্থানীয় ব্যবসার প্রসার", text: "তামাইয়ে বর্তমানে পাওয়ার লুম ও লুঙ্গির ব্যবসা রয়েছে। পৃথক ব্যবসাগুলো কখন ও কীভাবে গড়ে উঠেছে, তা অনুমানের বদলে তথ্যসূত্র থেকে জানতে হবে।", material: "যা খোঁজা হবে: ব্যবসার নথি ও প্রত্যক্ষ বিবরণ।" },
    modern: { title: "আধুনিক তামাই", text: "দৈনন্দিন জীবন, স্থানীয় জায়গা ও সামাজিক কর্মকাণ্ডের পরিবর্তন ছবি, নথি ও বাসিন্দাদের অভিজ্ঞতার মাধ্যমে সংরক্ষণ করা যায়।", material: "যা খোঁজা হবে: সমকালীন নথি ও সবার তোলা ছবি।" },
  },
  warLabel: "মুক্তিযুদ্ধের স্মরণে",
  warTitle: "সাক্ষ্য রাখার একটি স্থান।\nমনে রাখার একটি দায়িত্ব।",
  warText: "১৯৭১ সালের মুক্তিযুদ্ধের সঙ্গে যুক্ত স্মৃতি তামাই এবং বৃহত্তর বেলকুচি–সিরাজগঞ্জ এলাকার মানুষের স্মৃতির অংশ। নথি, স্থানীয় সাক্ষ্য, নাম, ছবি ও স্মৃতি যত্নে সংরক্ষণের জন্য এই অংশ রাখা হয়েছে।",
  warNote: "স্থানীয় নাম, স্থান ও ঘটনার বিবরণ স্পষ্ট তথ্যসূত্র এবং পর্যালোচনার পরই প্রকাশ করা হবে। নিচের স্থানগুলো ভবিষ্যৎ সংগ্রহের বিষয়, এই আর্কাইভে ইতিমধ্যে থাকা বিবরণ নয়।",
  warCollections: ["প্রত্যক্ষদর্শীর বিবরণ", "মুক্তিযোদ্ধাদের গল্প", "পুরোনো ছবি", "স্থানীয় স্মৃতিবিজড়িত স্থান", "নথিপত্র"],
  collectionPending: "উৎসসহ উপকরণের অপেক্ষায়",
  originLabel: "প্রজন্মের হাতে গড়া একটি জনপদ",
  originTitle: "উৎপত্তি, বসতি\nও বদলে যাওয়া ভূদৃশ্য।",
  originText: "একটি গ্রাম কীভাবে গড়ে ওঠে তা জানতে বসতি গড়া পরিবার, পাড়া-মহল্লার নাম এবং জমি, সড়ক, জলপথ ও সামাজিক জীবনের পরিবর্তন নিয়ে প্রশ্ন করতে হয়। তামাইয়ের ক্ষেত্রে স্থানীয় উপকরণ থেকে এসব প্রশ্নের উত্তর খুঁজতে হবে।",
  originThemes: ["পারিবারিক বসতির ধারা", "পাড়া-মহল্লা ও স্থানীয় এলাকা", "জমি, সড়ক ও জলপথ", "সামাজিক জীবনের পরিবর্তন"],
  nameTitle: "তামাই নামের উৎপত্তি",
  researchStatus: "কমিউনিটির গবেষণা চলছে",
  nameText: "এই আর্কাইভে নামের উৎপত্তি এখনো যাচাই করা হয়নি। ঐতিহাসিক ব্যাখ্যা দেওয়ার আগে ভিন্ন স্থানীয় বিবরণ সংগ্রহ, বক্তা বা উৎস উল্লেখ এবং প্রাপ্ত নথির সঙ্গে তুলনা করা যেতে পারে।",
  institutionsLabel: "যে স্থানগুলো নথি ধরে রাখে",
  institutionsTitle: "সময়ের পথে প্রতিষ্ঠান।",
  institutionsText: "নিবন্ধনখাতা, সভার বিবরণ, ছবি ও প্রতিষ্ঠানের অন্যান্য নথি গ্রামের বিকাশের সূত্র দিতে পারে। তথ্যসূত্রের সমর্থন পাওয়া গেলে নির্দিষ্ট নাম ও প্রতিষ্ঠার সাল যুক্ত হবে।",
  institutions: ["বিদ্যালয়", "মাদ্রাসা", "মসজিদ", "বাজার", "সামাজিক সংগঠন", "জনসাধারণের ও কমিউনিটির সুবিধাকেন্দ্র"],
  institutionLink: "প্রতিষ্ঠানের তালিকা দেখুন",
  institutionNote: "সবার অবদান ও উৎস পর্যালোচনার মাধ্যমে যাচাইকৃত প্রতিষ্ঠানের বিবরণ যুক্ত হবে।",
  voicesLabel: "মানুষের কণ্ঠে জীবন্ত আর্কাইভ",
  voicesTitle: "তামাইয়ের মানুষের স্মৃতি",
  voicesText: "প্রবীণ ও দীর্ঘদিনের বাসিন্দারা গ্রামের জীবনের নানা দিক সংরক্ষণে সাহায্য করতে পারেন: মানুষ কী করত, জায়গাগুলো কীভাবে বদলেছে, আর পরিবারের মনে কী রয়ে গেছে।",
  voicesTopics: ["ব্যক্তিগত স্মৃতি", "পারিবারিক গল্প", "পুরোনো রীতিনীতি", "গ্রামীণ জীবনের পরিবর্তন", "তাঁতশিল্পের স্মৃতি", "১৯৭১-এর স্মৃতিচারণ", "প্রতিষ্ঠানের ইতিহাস"],
  principleLabel: "মৌখিক ইতিহাস সংরক্ষণে আমাদের ভাবনা",
  principle: "স্মৃতি শোনার যোগ্য।\nতার প্রেক্ষাপটও রাখার যোগ্য।",
  principleText: "মৌখিক ইতিহাসের নিজস্ব মূল্য রয়েছে। কে বলছেন, কখন বলেছেন এবং কোনটি নিজের স্মৃতি আর কোনটি অন্যের কাছে শোনা—তা উল্লেখ করা হবে। লিখিত নথির সঙ্গে অমিল থাকলেও সাক্ষ্যকে সাক্ষ্য হিসেবেই চিহ্নিত রাখা হবে।",
  voicesNote: "এখানে এখনো কোনো সাক্ষাৎকার বা ব্যক্তিগত উদ্ধৃতি দেওয়া হয়নি। ভবিষ্যতের বিবরণ অনুমতি নিয়ে প্রকাশ করা হবে।",
  sourcesLabel: "গল্পের পেছনের উপকরণ",
  sourcesTitle: "তথ্যসূত্র ও প্রমাণ।",
  sourcesText: "উৎস দেখা গেলে ইতিহাস বুঝতে সুবিধা হয়। আর্কাইভে এই ধরনের উপকরণ সংরক্ষণের লক্ষ্য রয়েছে।",
  sources: [
    { title: "লিখিত নথি", description: "জানা থাকলে নথির লেখক, উদ্দেশ্য ও প্রেক্ষাপট।" },
    { title: "পুরোনো ছবি", description: "কে ছবিটি দিয়েছেন, কী দেখা যাচ্ছে এবং কখন তোলা হয়ে থাকতে পারে।" },
    { title: "বিদ্যালয়ের নথি", description: "বিদ্যালয় বা পরিবারের কাছে রাখা নিবন্ধনখাতা, প্রতিবেদন ও অন্যান্য উপকরণ।" },
    { title: "মসজিদ ও মাদ্রাসার নথি", description: "উৎস ও প্রেক্ষাপট চিহ্নিত করে রাখা প্রাতিষ্ঠানিক দলিল।" },
    { title: "জমি বা প্রশাসনিক নথি", description: "উৎস ও ঐতিহাসিক প্রেক্ষাপট যাচাই করা প্রাসঙ্গিক নথি।" },
    { title: "সংবাদপত্রের কাটিং", description: "কাটিংয়ের সঙ্গে পত্রিকার নাম, প্রতিবেদন ও তারিখ সংরক্ষণ।" },
    { title: "পারিবারিক সংগ্রহ", description: "চিঠি, কাগজপত্র ও ছবি—সেগুলোর উৎস সম্পর্কে পরিবারের বিবরণসহ।" },
    { title: "মৌখিক সাক্ষ্য", description: "বক্তার পরিচয়, ধারণের প্রেক্ষাপট এবং স্মৃতির সীমাবদ্ধতা।" },
    { title: "কমিউনিটির ছবি", description: "বিবরণ, উৎসের তথ্য ও অনুমতিসহ সমকালীন ছবি।" },
  ],
  sourceNote: "উৎসের ধরন আর যাচাইয়ের অবস্থা এক নয়। লিখিত উপকরণ অসম্পূর্ণ হতে পারে, আবার মৌখিক বিবরণেও মূল্যবান প্রমাণ মিলতে পারে। প্রতিটি বিবরণে উৎস, যাচাইয়ের অবস্থা ও অমীমাংসিত অমিল রাখা হবে।",
  sourceLegend: "আর্কাইভের লেবেল",
  contributeLabel: "ইতিহাসের বিবরণ পূর্ণ করতে সাহায্য করুন",
  contributeTitle: "আপনার রাখা উপকরণ\nআমাদের মনে রাখতে সাহায্য করতে পারে।",
  contributeText: "পুরোনো ছবি, পারিবারিক কাগজপত্র ও যত্নে মনে রাখা তথ্য আরও পূর্ণ ইতিহাস গড়তে সাহায্য করবে। সংশোধন স্বাগত; নাম ও তারিখের সঙ্গে যাচাই করা যায় এমন উৎস থাকা দরকার।",
  contributeItems: ["পুরোনো ছবি", "পারিবারিক নথি", "ঐতিহাসিক স্মৃতি", "প্রতিষ্ঠানের নথি", "সংশোধন", "সমর্থনকারী উৎসসহ নাম ও তারিখ"],
  contributeButton: "তামাইয়ের ইতিহাস সংরক্ষণে আপনার তথ্য দিন",
  contributeNote: "অবদান জমা দেওয়া এখনো চালু হয়নি। উপকরণের সঙ্গে উৎসের তথ্য ও শেয়ার করার অনুমতি রাখুন।",
};
export const historyTranslations = { en, bn } satisfies Record<Locale, typeof en>;
