import type { Locale } from "./translations";
import type { InstitutionCategory } from "@/types/institution";

const en = {
  title: "Institutions of Tamai",
  subtitle: "The places that educate, serve, connect and shape our community.",
  eyebrow: "THE PLACES WE SHARE",
  lead: "A community directory in preparation, and a place to preserve the histories behind the institutions of village life.",
  explore: "Explore the categories",
  heroArtLabel: "A COMMUNITY DIRECTORY",
  heroArtTitle: "Many places.\nA shared village life.",
  heroArtCaption: "An illustrative directory study. Local photographs and records will follow.",
  introLabel: "PART OF OUR SOCIAL HISTORY",
  introTitle: "Keeping a record of\nthe places that matter.",
  introText: "Institutions are part of Tamai’s social history. This section will document places of education and faith, markets and commercial centres, social and cultural organizations, health and public services, and other community institutions.",
  introNote: "Verified institution records will be added through community contributions and source review. The categories and example below do not represent a completed directory.",
  categoriesLabel: "EXPLORE BY PURPOSE",
  categoriesTitle: "At the heart of village life.",
  categoriesText: "Six collection areas, ready for the names, records and stories our community can help preserve.",
  categories: {
    education: { title: "Educational Institutions", description: "Places of learning, with space for their educational role, records and history.", examples: "Future listings: schools, madrasas and other educational institutions." },
    religion: { title: "Religious Institutions", description: "Places of worship and religious life, documented with their communities and sources.", examples: "Future listings: mosques and other religious institutions." },
    commerce: { title: "Markets & Commercial Centres", description: "Places of exchange and business that connect people through everyday trade.", examples: "Future listings: markets and commercial centres." },
    culture: { title: "Social & Cultural Organizations", description: "Groups that bring people together through cultural activity and social participation.", examples: "Future listings: social and cultural organizations." },
    services: { title: "Health & Public Services", description: "Institutions that support community wellbeing and access to public services.", examples: "Future listings: health and public service institutions." },
    community: { title: "Other Community Institutions", description: "Other shared places and organizations with a role in the life of the village.", examples: "Future listings: community facilities and other institutions." },
  } satisfies Record<InstitutionCategory, { title: string; description: string; examples: string }>,
  comingSoon: "Records coming soon",
  recordLabel: "A PLACE FOR EACH INSTITUTION’S STORY",
  recordTitle: "More than a name\nin a directory.",
  recordText: "Each future record will bring together a place’s beginnings, present-day role and source material. Missing information will remain clearly identified until it can be checked.",
  sampleLabel: "EXAMPLE RECORD · PLACEHOLDERS ONLY",
  sampleNote: "This demonstrates the record layout. It is not a real institution, a submitted entry or a verified listing.",
  fields: {
    name: "Institution name", category: "Category", year: "Established year", founder: "Founder / founding body", location: "Location",
    history: "Short history", role: "Current role", images: "Images", sourceType: "Source type", sourceDetails: "Source details",
    contributor: "Contributor", status: "Verification status",
  },
  placeholders: {
    name: "Institution name", category: "Category to be confirmed", year: "Year to be verified", founder: "Founding information pending",
    location: "Location to be verified", history: "Community documentation pending", role: "Present-day information pending",
    images: "Photographs with captions and permission will appear here.", sourceType: "Source type to be recorded",
    sourceDetails: "Supporting sources to be added", contributor: "Contributor details pending",
  },
  roleLabel: "INSTITUTIONS THROUGH TIME",
  roleTitle: "Village history,\nheld in everyday places.",
  roleText: "The history of an institution can help us understand how people learned, practised their faith, traded, gathered and accessed services. Registers, photographs and personal accounts can reveal changes in village life.",
  roleMore: "A founding record may tell one part of a story; the people who used a place may remember another. Both deserve context, and their differences should remain visible.",
  roleThemes: ["Education", "Religious life", "Trade", "Social development", "Public services", "Changes in village life"],
  historyLink: "Read our approach to history",
  statusLabel: "KNOWING WHAT A RECORD TELLS US",
  statusTitle: "Sources first.\nClear status, always.",
  statusText: "The directory follows the History archive’s approach: identify the source, keep its context and make uncertainty visible.",
  statuses: {
    verified: { label: "Verified", description: "Information checked against identified supporting sources, with the record’s scope made clear." },
    submitted: { label: "Community Submitted", description: "Material received from a community contributor. Submission alone does not mean it has been verified." },
    oral: { label: "Oral Account", description: "A spoken account with its narrator and context recorded. Its historical claims may still need corroboration." },
    review: { label: "Under Review", description: "Information awaiting source checks, comparison or clarification before a conclusion is reached." },
  },
  statusNote: "Source type and verification are different. An oral account is not automatically verified, and a written record still needs review. No real entries have been assigned these labels on this page yet.",
  contributeLabel: "HELP BUILD THE COMMUNITY RECORD",
  contributeTitle: "You may know the story\nbehind a familiar place.",
  contributeText: "A photograph, a founding document or a correction can help preserve the history of an institution. Community members will later be able to share what they know and the sources that support it.",
  contributeItems: ["Institution names", "Founding information", "Old photographs", "Founder information", "Historical documents", "Corrections", "Present-day information"],
  contributeButton: "Help document Tamai’s institutions",
  contributeNote: "Submissions are not open yet. Keep source details and permission to share with your material.",
  directoryLabel: "THE FUTURE DIRECTORY",
  directoryTitle: "A growing guide to our community.",
  directoryText: "A preview of how verified institution listings will be organized.",
  directoryNotice: "Directory preview only. Search and category filtering are not available yet.",
  searchLabel: "Search institutions", searchPlaceholder: "Search will be available later",
  filterLabel: "Category", allCategories: "All categories", countLabel: "Institution count", countPending: "Count pending",
  listingLabel: "Institution listings", emptyTitle: "The directory begins with our community.",
  emptyText: "Verified institution names and records will appear here after contributions and review. The example above is not included as a directory entry.",
  sampleLink: "See the example record",
};

const bn: typeof en = {
  title: "তামাইয়ের প্রতিষ্ঠানসমূহ",
  subtitle: "যে প্রতিষ্ঠানগুলো আমাদের শিক্ষা, সেবা, যোগাযোগ ও সামাজিক জীবনকে গড়ে তোলে।",
  eyebrow: "আমাদের আপন প্রতিষ্ঠান",
  lead: "কমিউনিটির একটি তালিকা তৈরির প্রস্তুতি—সঙ্গে গ্রামীণ জীবনের প্রতিষ্ঠানগুলোর ইতিহাস সংরক্ষণের একটি জায়গা।",
  explore: "প্রতিষ্ঠানের ধরনগুলো দেখুন",
  heroArtLabel: "কমিউনিটির প্রতিষ্ঠান তালিকা",
  heroArtTitle: "নানা প্রতিষ্ঠান।\nএক গ্রামের সামাজিক জীবন।",
  heroArtCaption: "প্রতিষ্ঠান তালিকার প্রতীকী চিত্র। স্থানীয় ছবি ও নথি পরে যুক্ত হবে।",
  introLabel: "আমাদের সামাজিক ইতিহাসের অংশ",
  introTitle: "যে জায়গাগুলো গুরুত্বপূর্ণ,\nতাদের কথা রাখি।",
  introText: "প্রতিষ্ঠানগুলো তামাইয়ের সামাজিক ইতিহাসের অংশ। এখানে শিক্ষা ও ধর্মীয় প্রতিষ্ঠান, বাজার ও বাণিজ্যিক কেন্দ্র, সামাজিক ও সাংস্কৃতিক সংগঠন, স্বাস্থ্য ও জনসেবা এবং অন্যান্য কমিউনিটি প্রতিষ্ঠানের তথ্য সংরক্ষণ করা হবে।",
  introNote: "সবার অবদান ও উৎস পর্যালোচনার মাধ্যমে যাচাইকৃত প্রতিষ্ঠানের বিবরণ যুক্ত হবে। নিচের বিভাগ ও উদাহরণ কোনো সম্পূর্ণ প্রতিষ্ঠান তালিকা নয়।",
  categoriesLabel: "কাজের ধরন অনুযায়ী দেখুন",
  categoriesTitle: "গ্রামীণ জীবনের কেন্দ্রবিন্দু।",
  categoriesText: "ছয়টি সংগ্রহের ক্ষেত্র—সবার সহায়তায় নাম, নথি ও গল্প সংরক্ষণের জন্য প্রস্তুত।",
  categories: {
    education: { title: "শিক্ষা প্রতিষ্ঠান", description: "শিক্ষার স্থান, যেখানে তাদের শিক্ষামূলক ভূমিকা, নথি ও ইতিহাস সংরক্ষণের সুযোগ থাকবে।", examples: "ভবিষ্যৎ তালিকা: বিদ্যালয়, মাদ্রাসা ও অন্যান্য শিক্ষা প্রতিষ্ঠান।" },
    religion: { title: "ধর্মীয় প্রতিষ্ঠান", description: "মানুষ ও তথ্যসূত্রসহ উপাসনা এবং ধর্মীয় জীবনের প্রতিষ্ঠানগুলোর পরিচিতি।", examples: "ভবিষ্যৎ তালিকা: মসজিদ ও অন্যান্য ধর্মীয় প্রতিষ্ঠান।" },
    commerce: { title: "বাজার ও বাণিজ্যিক কেন্দ্র", description: "লেনদেন ও ব্যবসার স্থান, যা দৈনন্দিন বাণিজ্যের মাধ্যমে মানুষকে যুক্ত করে।", examples: "ভবিষ্যৎ তালিকা: বাজার ও বাণিজ্যিক কেন্দ্র।" },
    culture: { title: "সামাজিক ও সাংস্কৃতিক সংগঠন", description: "সাংস্কৃতিক কর্মকাণ্ড ও সামাজিক অংশগ্রহণের মাধ্যমে মানুষকে এক করে এমন সংগঠন।", examples: "ভবিষ্যৎ তালিকা: সামাজিক ও সাংস্কৃতিক সংগঠন।" },
    services: { title: "স্বাস্থ্য ও জনসেবা", description: "মানুষের সুস্থতা ও জনসেবা পাওয়ার সুযোগে ভূমিকা রাখা প্রতিষ্ঠান।", examples: "ভবিষ্যৎ তালিকা: স্বাস্থ্য ও জনসেবামূলক প্রতিষ্ঠান।" },
    community: { title: "অন্যান্য গুরুত্বপূর্ণ প্রতিষ্ঠান", description: "গ্রামের জীবনে ভূমিকা রাখা অন্যান্য সংগঠন এবং সবার ব্যবহার্য স্থান।", examples: "ভবিষ্যৎ তালিকা: কমিউনিটির সুবিধাকেন্দ্র ও অন্যান্য প্রতিষ্ঠান।" },
  },
  comingSoon: "প্রতিষ্ঠানের বিবরণ শিগগিরই আসছে",
  recordLabel: "প্রতিটি প্রতিষ্ঠানের গল্পের জন্য",
  recordTitle: "তালিকায় শুধু একটি\nনামের চেয়েও বেশি।",
  recordText: "প্রতিটি ভবিষ্যৎ বিবরণে প্রতিষ্ঠানের সূচনা, বর্তমান ভূমিকা ও তথ্যসূত্র একত্রে থাকবে। যাচাই করা না গেলে অনুপস্থিত তথ্য স্পষ্টভাবেই চিহ্নিত থাকবে।",
  sampleLabel: "উদাহরণ বিবরণ · কেবল নমুনা ঘর",
  sampleNote: "এটি বিবরণের বিন্যাস দেখানোর উদাহরণ। এটি কোনো বাস্তব প্রতিষ্ঠান, জমা দেওয়া তথ্য বা যাচাইকৃত তালিকাভুক্ত প্রতিষ্ঠান নয়।",
  fields: {
    name: "প্রতিষ্ঠানের নাম", category: "ধরন", year: "প্রতিষ্ঠার সাল", founder: "প্রতিষ্ঠাতা / প্রতিষ্ঠাকারী সংস্থা", location: "অবস্থান",
    history: "সংক্ষিপ্ত ইতিহাস", role: "বর্তমান ভূমিকা", images: "ছবি", sourceType: "উৎসের ধরন", sourceDetails: "তথ্যসূত্রের বিবরণ",
    contributor: "তথ্যদাতা", status: "যাচাইয়ের অবস্থা",
  },
  placeholders: {
    name: "প্রতিষ্ঠানের নাম", category: "ধরন নিশ্চিত করা বাকি", year: "প্রতিষ্ঠার সাল যাচাই করা হবে", founder: "প্রতিষ্ঠার তথ্যের অপেক্ষায়",
    location: "অবস্থান যাচাই করা হবে", history: "কমিউনিটির তথ্য সংরক্ষণের অপেক্ষায়", role: "বর্তমান তথ্যের অপেক্ষায়",
    images: "বিবরণ ও অনুমতিসহ ছবি এখানে যুক্ত হবে।", sourceType: "উৎসের ধরন সংরক্ষণ করা হবে",
    sourceDetails: "সমর্থনকারী তথ্যসূত্র যুক্ত করা হবে", contributor: "তথ্যদাতার বিবরণের অপেক্ষায়",
  },
  roleLabel: "সময়ের পথে প্রতিষ্ঠান",
  roleTitle: "দৈনন্দিন জীবনের স্থানেই\nগ্রামের ইতিহাস।",
  roleText: "প্রতিষ্ঠানের ইতিহাস থেকে মানুষের শিক্ষা, ধর্মচর্চা, বাণিজ্য, মিলন ও সেবা পাওয়ার কথা জানা যায়। নিবন্ধনখাতা, ছবি ও ব্যক্তিগত বিবরণ গ্রামীণ জীবনের পরিবর্তন তুলে ধরতে পারে।",
  roleMore: "প্রতিষ্ঠার নথি গল্পের একটি দিক বলতে পারে; যে মানুষ সেখানে গিয়েছেন, তাঁর স্মৃতিতে থাকতে পারে আরেকটি দিক। দুটোরই প্রেক্ষাপট দরকার, আর অমিল থাকলে তা দৃশ্যমান রাখা উচিত।",
  roleThemes: ["শিক্ষা", "ধর্মীয় জীবন", "বাণিজ্য", "সামাজিক বিকাশ", "জনসেবা", "গ্রামীণ জীবনের পরিবর্তন"],
  historyLink: "ইতিহাস সংরক্ষণে আমাদের ভাবনা জানুন",
  statusLabel: "প্রতিষ্ঠানের বিবরণ যা জানায়",
  statusTitle: "আগে তথ্যসূত্র।\nযাচাইয়ের অবস্থা সবসময় স্পষ্ট।",
  statusText: "ইতিহাস আর্কাইভের একই নীতি এখানে: উৎস চিহ্নিত করা, প্রেক্ষাপট রাখা এবং অনিশ্চয়তা স্পষ্ট করা।",
  statuses: {
    verified: { label: "যাচাইকৃত", description: "চিহ্নিত সমর্থনকারী উৎসের সঙ্গে তথ্য মিলিয়ে দেখা হয়েছে এবং বিবরণের পরিধি স্পষ্ট করা হয়েছে।" },
    submitted: { label: "কমিউনিটি থেকে জমা দেওয়া", description: "কমিউনিটির কারও কাছ থেকে পাওয়া উপকরণ। জমা দেওয়া মানেই যাচাইকৃত নয়।" },
    oral: { label: "মৌখিক বিবরণ", description: "বক্তা ও প্রেক্ষাপটসহ সংরক্ষিত মুখে বলা কথা। ঐতিহাসিক দাবির জন্য আরও সমর্থন দরকার হতে পারে।" },
    review: { label: "যাচাইাধীন", description: "সিদ্ধান্তে পৌঁছানোর আগে উৎস যাচাই, তুলনা বা ব্যাখ্যার অপেক্ষায় থাকা তথ্য।" },
  },
  statusNote: "উৎসের ধরন ও যাচাই এক বিষয় নয়। মৌখিক বিবরণ নিজে থেকেই যাচাইকৃত হয় না, আর লিখিত নথিও পর্যালোচনা করতে হয়। এই পাতায় কোনো বাস্তব প্রতিষ্ঠানের বিবরণে এখনো এসব লেবেল দেওয়া হয়নি।",
  contributeLabel: "কমিউনিটির বিবরণ গড়তে সাহায্য করুন",
  contributeTitle: "চেনা কোনো প্রতিষ্ঠানের\nগল্প হয়তো আপনার জানা।",
  contributeText: "একটি ছবি, প্রতিষ্ঠার নথি বা সংশোধন কোনো প্রতিষ্ঠানের ইতিহাস সংরক্ষণে সাহায্য করতে পারে। ভবিষ্যতে সবাই নিজের জানা তথ্য ও তার সমর্থনকারী উৎস শেয়ার করতে পারবেন।",
  contributeItems: ["প্রতিষ্ঠানের নাম", "প্রতিষ্ঠার তথ্য", "পুরোনো ছবি", "প্রতিষ্ঠাতার তথ্য", "ঐতিহাসিক নথি", "সংশোধন", "বর্তমান তথ্য"],
  contributeButton: "তামাইয়ের প্রতিষ্ঠান সম্পর্কে তথ্য দিন",
  contributeNote: "অবদান জমা দেওয়া এখনো চালু হয়নি। উপকরণের সঙ্গে উৎসের তথ্য ও শেয়ার করার অনুমতি রাখুন।",
  directoryLabel: "ভবিষ্যতের প্রতিষ্ঠান তালিকা",
  directoryTitle: "আমাদের কমিউনিটির পরিচিতি।",
  directoryText: "যাচাইকৃত প্রতিষ্ঠানের বিবরণ যেভাবে সাজানো হবে, তার প্রাথমিক চিত্র।",
  directoryNotice: "এটি শুধু তালিকার প্রাথমিক চিত্র। অনুসন্ধান ও ধরন অনুযায়ী বাছাই এখনো চালু হয়নি।",
  searchLabel: "প্রতিষ্ঠান খুঁজুন", searchPlaceholder: "অনুসন্ধান পরে চালু হবে",
  filterLabel: "ধরন", allCategories: "সব ধরনের প্রতিষ্ঠান", countLabel: "প্রতিষ্ঠানের সংখ্যা", countPending: "সংখ্যা নির্ধারণ বাকি",
  listingLabel: "প্রতিষ্ঠানের তালিকা", emptyTitle: "সবার অংশগ্রহণেই তালিকার শুরু।",
  emptyText: "অবদান সংগ্রহ ও পর্যালোচনার পর যাচাইকৃত প্রতিষ্ঠানের নাম ও বিবরণ এখানে আসবে। ওপরের উদাহরণটি তালিকার কোনো প্রতিষ্ঠান হিসেবে গণনা করা হয়নি।",
  sampleLink: "বিবরণের উদাহরণ দেখুন",
};
export const institutionTranslations = { en, bn } satisfies Record<Locale, typeof en>;
