import type { Locale } from "./translations";

const en = {
  title: "Lungi & Textile Heritage",
  subtitle: "A living tradition woven through generations.",
  eyebrow: "THE FABRIC OF TAMAI",
  lead: "From the knowledge of the handloom to the rhythm of the power loom, textile work is part of Tamai’s story — and its everyday life.",
  explore: "Follow the thread",
  heroCaption: "A study in checks, stripes and woven borders.",
  illustration: "Illustrative patterns · not archival fabric samples",
  contents: "ON THIS PAGE",
  chapters: ["Our textile identity", "Across generations", "How a lungi is made", "Pattern & colour", "People & livelihoods", "Community archive"],
  introLabel: "MORE THAN A PIECE OF CLOTH",
  introTitle: "A craft. A livelihood.\nA shared identity.",
  introLead: "In Tamai, weaving and lungi production connect craft knowledge with the practical work of earning a living.",
  introText: "The village’s textile identity includes both a long weaving tradition and a strong present-day power loom business. As production has changed over time, the making and trading of cloth have remained part of local business culture.",
  introNote: "This is a starting point for a community archive. The details of particular workshops, families and changes in production will be documented through local accounts and records.",
  historyLabel: "ACROSS GENERATIONS",
  historyTitle: "From handloom\nto power loom.",
  historyText: "A way to explore a changing tradition, without assigning dates to stories that still need to be recorded.",
  historyNote: "An undated outline, not a verified local chronology. Community records will help establish when and how these changes took place in Tamai.",
  history: [
    { label: "THE ROOTS", title: "Traditional weaving roots", text: "Tamai’s textile story begins with its connection to weaving. The origins and early practices are an important part of the archive still to be documented." },
    { label: "ACROSS GENERATIONS", title: "Handloom culture", text: "Handloom weaving brings together skill, rhythm and familiarity with thread. Memories of this work can help preserve knowledge beyond the finished cloth." },
    { label: "OVER TIME", title: "Gradual mechanization", text: "The move toward mechanized weaving is a thread to trace through workshop histories, equipment records and the memories of those who experienced it." },
    { label: "A CHANGING CRAFT", title: "Power loom production", text: "Power looms are an important part of Tamai’s present-day textile identity, alongside the knowledge involved in preparing, operating and caring for the looms." },
    { label: "TODAY", title: "Commercial lungi production", text: "Lungi production and trade connect the village’s textile work with business life. Individual businesses and their histories await community documentation." },
  ],
  processLabel: "FROM THREAD TO CLOTH",
  processTitle: "How a lungi is made.",
  processText: "A general overview of the textile process associated with local production. Workshop methods and the order of some tasks vary; Tamai-specific practices remain to be documented.",
  processNote: "Pattern planning begins before weaving; checks emerge as the chosen threads are woven together. The stages below are a simplified guide, not a technical specification.",
  process: [
    { title: "Yarn preparation", text: "Yarn is selected and prepared for the intended cloth and colour arrangement." },
    { title: "Warping", text: "Lengthwise threads are arranged in an ordered set, ready for the loom." },
    { title: "Loom setup", text: "The warp is placed on the loom and the threads are set up for weaving." },
    { title: "Weaving", text: "Crosswise weft threads interlace with the lengthwise warp to form cloth." },
    { title: "Pattern & checking", text: "The planned checks or stripes take shape during weaving, and the cloth is inspected." },
    { title: "Finishing", text: "Woven cloth is prepared for use; the finishing methods depend on the fabric and workshop." },
    { title: "Folding & packing", text: "The finished cloth is folded and prepared for handling, sale or distribution." },
  ],
  processSource: "General weaving reference · University of Cambridge (PDF, pp. 7–8)",
  patternsLabel: "A LANGUAGE OF THREADS",
  patternsTitle: "The familiar rhythm\nof checks and stripes.",
  patternsText: "Repeated lines, crossing colours and a considered border give lungi cloth its visual rhythm. Here, those ideas also shape the Tamai website: a quiet grid, a striped edge, a warm meeting of colours.",
  patterns: [
    { title: "Checks", text: "Crossing bands create a repeating grid, from small checks to broader blocks." },
    { title: "Stripes", text: "Parallel lines bring direction and rhythm to the surface of the cloth." },
    { title: "Colour & borders", text: "Contrasting colours and framed edges give a pattern its character." },
  ],
  patternNote: "These illustrative studies interpret a familiar textile vocabulary. They are not named traditional designs or authenticated Tamai samples. Community contributions can document the patterns used locally.",
  peopleLabel: "THE PEOPLE BEHIND THE FABRIC",
  peopleTitle: "Every length of cloth\nhas people behind it.",
  peopleText: "A textile heritage archive should hold the voices of the people who make, maintain, trade and live alongside this work. Individual stories will be added with community contributions and permission.",
  roles: ["Weavers", "Loom operators", "Craftspeople", "Small business owners", "Traders", "Families connected to textile work"],
  peopleLink: "Help preserve a story",
  economyLabel: "WORK & EVERYDAY LIFE",
  economyTitle: "Woven into the life\nof the village.",
  economyText: "The lungi and power loom industry is connected with local livelihoods, employment, family businesses and trade. It is part of how Tamai works, as well as how the village is known.",
  economyMore: "Future accounts can explore the relationships between workshops, workers, families and markets. We will add economic detail only when it can be supported by reliable local sources.",
  archiveLabel: "A HERITAGE WE CAN PRESERVE TOGETHER",
  archiveTitle: "There is more to this story.\nPerhaps you hold a thread.",
  archiveText: "An old loom photograph, a family memory or a workshop’s story can help make this record more complete. Community submissions are being prepared.",
  archiveButton: "Help document Tamai’s textile heritage",
  contributions: ["Old loom photographs", "Factory & workshop photographs", "Family stories", "Business histories", "Pattern samples", "Memories of the handloom era", "Information about local textile businesses"],
  archiveNote: "Keep the source, approximate date if known, and permission to share with your material. Submissions are not open yet.",
  galleryLabel: "THE TEXTILE PHOTO ARCHIVE",
  galleryTitle: "Space for the real stories.",
  galleryText: "Photographs from Tamai will give this collection its detail and its human faces.",
  gallery: ["Traditional loom", "Power loom", "Yarn", "Lungi patterns", "Workshop & factory", "Workers", "Old textile photographs"],
  galleryNote: "Archive spaces awaiting real photographs, captions and source details.",
};

const bn: typeof en = {
  title: "লুঙ্গি ও তাঁতশিল্পের ঐতিহ্য",
  subtitle: "প্রজন্মের পর প্রজন্ম ধরে বোনা এক জীবন্ত ঐতিহ্য।",
  eyebrow: "তামাইয়ের বুনন",
  lead: "হাততাঁতের অভিজ্ঞতা থেকে পাওয়ার লুমের ছন্দ—বস্ত্রশিল্প তামাইয়ের গল্পের অংশ, দৈনন্দিন জীবনেরও অংশ।",
  explore: "বুননের গল্প জানুন",
  heroCaption: "চেক, ডোরা ও বোনা পাড়ের নকশার নমুনা।",
  illustration: "প্রতীকী নকশা · আর্কাইভের কাপড়ের নমুনা নয়",
  contents: "এই পাতায়",
  chapters: ["তাঁতশিল্পে আমাদের পরিচয়", "প্রজন্মের পথ ধরে", "লুঙ্গি তৈরির ধাপ", "নকশা ও রং", "মানুষ ও জীবিকা", "কমিউনিটি আর্কাইভ"],
  introLabel: "শুধু এক টুকরো কাপড় নয়",
  introTitle: "একটি শিল্প। একটি জীবিকা।\nআমাদের পরিচয়।",
  introLead: "তামাইয়ে তাঁত ও লুঙ্গি উৎপাদন কারুশিল্পের অভিজ্ঞতাকে জীবিকা উপার্জনের দৈনন্দিন কাজের সঙ্গে যুক্ত করে।",
  introText: "গ্রামের বস্ত্রশিল্পের পরিচয়ে যেমন দীর্ঘ তাঁতের ঐতিহ্য রয়েছে, তেমনি রয়েছে বর্তমানের শক্তিশালী পাওয়ার লুম ব্যবসা। সময়ের সঙ্গে উৎপাদন বদলালেও কাপড় তৈরি ও বেচাকেনা স্থানীয় ব্যবসায়িক সংস্কৃতির অংশ হয়ে আছে।",
  introNote: "এটি সবার অংশগ্রহণে একটি আর্কাইভ তৈরির সূচনা। নির্দিষ্ট কর্মশালা, পরিবার ও উৎপাদনের পরিবর্তনের বিবরণ স্থানীয় মানুষের কথা ও নথির মাধ্যমে সংরক্ষণ করা হবে।",
  historyLabel: "প্রজন্মের পথ ধরে",
  historyTitle: "হাততাঁত থেকে\nপাওয়ার লুম।",
  historyText: "পরিবর্তনশীল একটি ঐতিহ্যকে জানার চেষ্টা—যে গল্প এখনো নথিবদ্ধ হয়নি, তার সঙ্গে অনুমানভিত্তিক সাল জুড়ে না দিয়ে।",
  historyNote: "এটি সালবিহীন একটি রূপরেখা, যাচাইকৃত স্থানীয় কালপঞ্জি নয়। তামাইয়ে কখন ও কীভাবে পরিবর্তনগুলো হয়েছে, তা স্থানীয় নথি ও স্মৃতি থেকে জানা যাবে।",
  history: [
    { label: "শিকড়ের কথা", title: "তাঁতের ঐতিহ্য", text: "তামাইয়ের বস্ত্রশিল্পের গল্প তাঁতের সঙ্গে তার সম্পর্ককে ঘিরে। এই শিল্পের সূচনা ও পুরোনো চর্চার বিবরণ এখনো আর্কাইভে সংরক্ষণের অপেক্ষায়।" },
    { label: "প্রজন্ম থেকে প্রজন্মে", title: "হাততাঁতের সংস্কৃতি", text: "হাততাঁতের বুননে মিশে থাকে দক্ষতা, ছন্দ ও সুতো চেনার অভিজ্ঞতা। এই কাজের স্মৃতি ধরে রাখলে কাপড়ের বাইরেও কারুশিল্পের জ্ঞান সংরক্ষিত হবে।" },
    { label: "সময়ের সঙ্গে", title: "ধীরে ধীরে যান্ত্রিকীকরণ", text: "যন্ত্রচালিত বুননের দিকে পরিবর্তনের গল্প খুঁজতে হবে কর্মশালার ইতিহাস, যন্ত্রপাতির নথি এবং পরিবর্তন দেখেছেন এমন মানুষের স্মৃতিতে।" },
    { label: "বদলে যাওয়া শিল্প", title: "পাওয়ার লুমে উৎপাদন", text: "পাওয়ার লুম তামাইয়ের বর্তমান বস্ত্রশিল্পের পরিচয়ের একটি গুরুত্বপূর্ণ অংশ। এর সঙ্গে যুক্ত রয়েছে তাঁত প্রস্তুত, চালনা ও যত্নের অভিজ্ঞতা।" },
    { label: "বর্তমান সময়", title: "বাণিজ্যিক লুঙ্গি উৎপাদন", text: "লুঙ্গি উৎপাদন ও বাণিজ্য গ্রামের বস্ত্রশিল্পকে ব্যবসায়িক জীবনের সঙ্গে যুক্ত করে। নির্দিষ্ট ব্যবসাপ্রতিষ্ঠানের ইতিহাস সবার অংশগ্রহণে সংরক্ষণ করা হবে।" },
  ],
  processLabel: "সুতো থেকে কাপড়",
  processTitle: "যেভাবে লুঙ্গি তৈরি হয়।",
  processText: "স্থানীয় উৎপাদনের সঙ্গে সম্পর্কিত বস্ত্র তৈরির সাধারণ ধাপের পরিচিতি। কর্মশালাভেদে পদ্ধতি ও কিছু ধাপের ক্রম বদলাতে পারে; তামাইয়ের নির্দিষ্ট প্রক্রিয়া এখনো নথিবদ্ধ করা বাকি।",
  processNote: "নকশার পরিকল্পনা বুননের আগেই শুরু হয়; নির্ধারিত সুতোর বুননে চেক ফুটে ওঠে। নিচের ধাপগুলো সহজ পরিচিতি, কারিগরি নির্দেশনা নয়।",
  process: [
    { title: "সুতো প্রস্তুত", text: "কাপড় ও রঙের পরিকল্পনা অনুযায়ী সুতো বেছে নিয়ে প্রস্তুত করা হয়।" },
    { title: "টানা তৈরি", text: "তাঁতে তোলার জন্য লম্বালম্বি সুতোগুলো নির্দিষ্ট ক্রমে সাজানো হয়।" },
    { title: "তাঁত প্রস্তুত", text: "তাঁতে টানা বসিয়ে সুতোগুলো বুননের উপযোগী করে সাজানো হয়।" },
    { title: "বুনন", text: "লম্বালম্বি টানার সুতোর সঙ্গে আড়াআড়ি পড়েনের সুতো মিলিয়ে কাপড় বোনা হয়।" },
    { title: "নকশা ও পরীক্ষা", text: "বুননের সময় পরিকল্পিত চেক বা ডোরা ফুটে ওঠে এবং কাপড় পরীক্ষা করা হয়।" },
    { title: "ফিনিশিং", text: "বোনা কাপড় ব্যবহারের উপযোগী করা হয়; কাপড় ও কর্মশালাভেদে পদ্ধতি আলাদা হতে পারে।" },
    { title: "ভাঁজ ও প্যাকিং", text: "তৈরি কাপড় ভাঁজ করে বিক্রি, সরবরাহ বা বহনের জন্য প্রস্তুত করা হয়।" },
  ],
  processSource: "সাধারণ বুননের তথ্যসূত্র · কেমব্রিজ বিশ্ববিদ্যালয় (পিডিএফ, পৃষ্ঠা ৭–৮)",
  patternsLabel: "সুতোর নিজস্ব ভাষা",
  patternsTitle: "চেক আর ডোরার\nচেনা ছন্দ।",
  patternsText: "রেখার পুনরাবৃত্তি, রঙের মিলন আর যত্নে সাজানো পাড় লুঙ্গির নকশায় ছন্দ আনে। তামাই ওয়েবসাইটেও এই ভাবনা রয়েছে: হালকা ছক, ডোরাকাটা প্রান্ত আর উষ্ণ রঙের মিলন।",
  patterns: [
    { title: "চেক", text: "আড়াআড়ি ও লম্বালম্বি রেখার মিলনে ছোট চেক থেকে বড় ঘরের নকশা তৈরি হয়।" },
    { title: "ডোরা", text: "পাশাপাশি রেখা কাপড়ের ওপর দিক ও ছন্দের অনুভূতি তৈরি করে।" },
    { title: "রং ও পাড়", text: "ভিন্ন রঙের মিলন ও প্রান্তের বুনন নকশাকে নিজস্ব চেহারা দেয়।" },
  ],
  patternNote: "এগুলো পরিচিত বস্ত্রনকশা থেকে অনুপ্রাণিত প্রতীকী নমুনা। এগুলো কোনো নামযুক্ত ঐতিহ্যবাহী নকশা বা যাচাইকৃত তামাইয়ের নমুনা নয়। স্থানীয় নকশাগুলো সবার অবদানে নথিবদ্ধ করা যাবে।",
  peopleLabel: "কাপড়ের পেছনের মানুষ",
  peopleTitle: "প্রতিটি কাপড়ের সঙ্গে\nজড়িয়ে আছে মানুষ।",
  peopleText: "যাঁরা কাপড় তৈরি করেন, যন্ত্রের যত্ন নেন, বাণিজ্য করেন এবং এই কাজের সঙ্গে জীবন কাটান—এই আর্কাইভে তাঁদের কণ্ঠ থাকা দরকার। সবার অবদান ও অনুমতি নিয়ে ব্যক্তিগত গল্প যুক্ত করা হবে।",
  roles: ["তাঁতি", "পাওয়ার লুম অপারেটর", "কারিগর", "ক্ষুদ্র ব্যবসায়ী", "কাপড়ের বণিক", "বস্ত্রশিল্পের সঙ্গে যুক্ত পরিবার"],
  peopleLink: "একটি গল্প সংরক্ষণে সাহায্য করুন",
  economyLabel: "কাজ ও দৈনন্দিন জীবন",
  economyTitle: "গ্রামের জীবনে\nবোনা এক শিল্প।",
  economyText: "লুঙ্গি ও পাওয়ার লুম শিল্পের সঙ্গে স্থানীয় জীবিকা, কর্মসংস্থান, পারিবারিক ব্যবসা ও বাণিজ্যের সম্পর্ক রয়েছে। তামাইয়ের কর্মজীবন ও গ্রামের পরিচয়—দুই ক্ষেত্রেই এটি গুরুত্বপূর্ণ।",
  economyMore: "ভবিষ্যতের বিবরণে কর্মশালা, শ্রমজীবী মানুষ, পরিবার ও বাজারের সম্পর্ক তুলে ধরা যাবে। নির্ভরযোগ্য স্থানীয় তথ্যসূত্র পাওয়া গেলেই অর্থনৈতিক তথ্য যুক্ত করা হবে।",
  archiveLabel: "একসঙ্গে সংরক্ষণ করি ঐতিহ্য",
  archiveTitle: "গল্পের অনেকটাই এখনো বাকি।\nহয়তো একটি সূত্র আপনার কাছেই।",
  archiveText: "পুরোনো তাঁতের ছবি, পরিবারের স্মৃতি বা কোনো কর্মশালার গল্প এই সংকলনকে পূর্ণ করতে পারে। সবার অবদান জমা দেওয়ার ব্যবস্থা তৈরি হচ্ছে।",
  archiveButton: "তামাইয়ের তাঁত ও লুঙ্গি ঐতিহ্য সংরক্ষণে তথ্য দিন",
  contributions: ["পুরোনো তাঁতের ছবি", "কারখানা ও কর্মশালার ছবি", "পারিবারিক গল্প", "ব্যবসার ইতিহাস", "নকশার নমুনা", "হাততাঁতের সময়ের স্মৃতি", "স্থানীয় বস্ত্র ব্যবসার তথ্য"],
  archiveNote: "উপকরণের সঙ্গে উৎস, জানা থাকলে আনুমানিক সময় এবং শেয়ার করার অনুমতি রাখুন। অবদান জমা দেওয়া এখনো চালু হয়নি।",
  galleryLabel: "তাঁতশিল্পের ছবির আর্কাইভ",
  galleryTitle: "আসল গল্পের জন্য জায়গা।",
  galleryText: "তামাইয়ের ছবি এই সংগ্রহে আনবে বাস্তব বিবরণ ও আপন মানুষের মুখ।",
  gallery: ["ঐতিহ্যবাহী তাঁত", "পাওয়ার লুম", "সুতো", "লুঙ্গির নকশা", "কর্মশালা ও কারখানা", "শ্রমজীবী মানুষ", "পুরোনো বস্ত্রশিল্পের ছবি"],
  galleryNote: "আসল ছবি, বিবরণ ও তথ্যসূত্রের অপেক্ষায় আর্কাইভের এই স্থানগুলো।",
};
export const textileTranslations = { en, bn } satisfies Record<Locale, typeof en>;
