"use client";
import { useRef, useState } from "react";
import { useLanguage } from "./language-provider";
import { useContributionDraft, type ContributionDraft } from "./contribution-draft-provider";
import { PublicShell, PublicHero, ArchiveStatusBadge } from "./public-shared";
import { SectionHeading } from "./section-heading";
import { archiveStatuses } from "@/types/archive";
const typeIds=["history","story","institution","photo","textile","culture","correction","other"];
export function ContributePage(){
 const {copy}=useLanguage();const t=copy.public.contribution; const c=copy.public.common;
 const {draft,setDraft}=useContributionDraft();const [submitted,setSubmitted]=useState(false);const result=useRef<HTMLParagraphElement>(null);
 function update<K extends keyof ContributionDraft>(key:K,value:ContributionDraft[K]){setDraft(d=>({...d,[key]:value}));setSubmitted(false);}
 const fields=["title","description","period","location","source","name","email","phone","notes"] as const;
 const required=new Set<string>(["title","description","source","name","email"]);
 return <PublicShell><PublicHero {...t} target="#contribution-types"/>
  <section className="public-intro"><div className="container public-columns"><SectionHeading eyebrow={t.introLabel} title={t.introTitle}/><p>{t.intro}</p></div></section>
  <section className="container section" id="contribution-types"><h2>{t.typesTitle}</h2><div className="contribution-types">{t.types.map((label,i)=><a href="#contribution-form" key={typeIds[i]} onClick={()=>{update("type",typeIds[i]);document.getElementById("contribution-type")?.focus({preventScroll:true});}}><span aria-hidden="true">＋</span>{label}<span aria-hidden="true">↓</span></a>)}</div></section>
  <section className="public-tinted section" id="contribution-form"><div className="container contribution-form-layout"><div><SectionHeading eyebrow={t.formLabel} title={t.formTitle}/><p className="public-notice" id="form-notice">{t.formNotice}</p></div><form aria-describedby="form-notice" onSubmit={event=>{event.preventDefault();setSubmitted(true);requestAnimationFrame(()=>result.current?.focus());}}><p className="form-required">{t.required}</p><div className="contribution-fields"><label className="field-wide" htmlFor="contribution-type">{t.fields.type} *<select id="contribution-type" required value={draft.type} onChange={e=>update("type",e.target.value)}><option value="">{t.select}</option>{t.types.map((label,i)=><option key={typeIds[i]} value={typeIds[i]}>{label}</option>)}</select></label>{fields.map(key=><label key={key} className={["title","description","source","notes"].includes(key)?"field-wide":""} htmlFor={`contribution-${key}`}>{t.fields[key]}{required.has(key)?" *":!["phone","notes"].includes(key)?` (${t.optional})`:""}{key==="description"||key==="notes"?<textarea id={`contribution-${key}`} rows={key==="description"?7:3} required={required.has(key)} maxLength={30000} value={draft[key]} onChange={e=>update(key,e.target.value)}/>:<input id={`contribution-${key}`} type={key==="email"?"email":key==="phone"?"tel":"text"} autoComplete={key==="name"?"name":key==="email"?"email":key==="phone"?"tel":"off"} required={required.has(key)} maxLength={1000} value={draft[key]} onChange={e=>update(key,e.target.value)}/>}</label>)}</div><div className="upload-placeholders">{[t.images,t.documents].map(label=><div key={label}><h3>{label}</h3><p>{t.uploadNote}</p></div>)}</div><label className="form-check"><input type="checkbox" required checked={draft.faith} onChange={e=>update("faith",e.target.checked)}/><span>{t.faith} *</span></label><label className="form-check"><input type="checkbox" checked={draft.permission} onChange={e=>update("permission",e.target.checked)}/><span>{t.permission}</span></label><button type="submit" className="button button-green">{t.submit}<span aria-hidden="true">→</span></button>{submitted&&<p ref={result} tabIndex={-1} role="status" className="submission-result">{t.result}</p>}</form></div></section>
  <section className="container section"><SectionHeading eyebrow={t.futureLabel} title={t.futureTitle} text={t.futureText}/><ol className="public-workflow">{t.workflow.map(item=><li key={item}>{item}</li>)}</ol></section>
  <section className="public-trust section"><div className="container"><div className="public-columns"><SectionHeading eyebrow={t.trustLabel} title={t.trustTitle}/><p>{t.trustText}</p></div><ol className="moderation-workflow">{t.moderation.map(item=><li key={item}>{item}</li>)}</ol><h3>{t.statusTitle}</h3><p>{t.statusText}</p><dl className="public-status-legend">{archiveStatuses.map(status=><div key={status}><dt><ArchiveStatusBadge status={status}/></dt><dd>{c.status[status].text}</dd></div>)}</dl></div></section>
 </PublicShell>;
}
