"use client";
import { useState } from "react";
import { useLanguage } from "./language-provider";
import { Arrow, Icon } from "./icon";

const anchors = ["home", "history", "culture", "textile", "institutions", "stories", "gallery", "contribute"];
function Wordmark() { const { copy } = useLanguage(); return <a href="#home" className="wordmark"><span className="brand-mark" aria-hidden="true">▥</span>{copy.name}<span className="brand-dot">.</span></a>; }
function Header() {
  const { copy, locale, setLocale } = useLanguage();
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="container header-inner"><Wordmark />
    <nav aria-label={copy.menu} className="desktop-nav">{copy.nav.map((label, i) => <a key={anchors[i]} href={`#${anchors[i]}`} className={i === 0 ? "current" : i === 7 ? "nav-contribute" : ""}>{label}</a>)}</nav>
    <div className="header-actions"><div className="language-switch" role="group" aria-label={copy.language}><button lang="en" aria-pressed={locale === "en"} onClick={() => setLocale("en")}>EN</button><span aria-hidden="true">/</span><button lang="bn" aria-pressed={locale === "bn"} onClick={() => setLocale("bn")}>বাংলা</button></div><button className="menu-button" aria-expanded={open} aria-controls="mobile-nav" onClick={() => setOpen(!open)}>{open ? copy.close : copy.menu}<span aria-hidden="true">{open ? "×" : "☰"}</span></button></div>
    <nav id="mobile-nav" aria-label={copy.menu} className="mobile-nav" hidden={!open}>{copy.nav.map((label, i) => <a key={anchors[i]} href={`#${anchors[i]}`} onClick={() => setOpen(false)}>{label}</a>)}</nav>
  </div></header>;
}
function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p className="section-description">{text}</p>}</div>; }

export function Home() {
  const { copy: t, locale } = useLanguage();
  const [contributionOpen, setContributionOpen] = useState(false);
  const categoryAnchors = ["history", "culture", "textile", "institutions", "stories", "gallery"];
  return <><a className="skip-link" href="#main">{t.skip}</a><Header /><main id="main">
    <section className="hero container" id="home"><div className="hero-copy"><p className="eyebrow location"><span aria-hidden="true">◇</span> {t.location}</p><p className="hero-kicker">{t.eyebrow}</p><h1>{t.name}<span>.</span></h1><h2>{t.tagline}</h2><p className="hero-description">{t.intro}</p><div className="hero-buttons"><a className="button button-green" href="#explore">{t.explore}<span aria-hidden="true">↓</span></a><a className="text-link" href="#contribute">{t.share}<Arrow /></a></div></div>
      <figure className="hero-art"><div className="art-border"><div className="woven-panel"><div className="woven-sun"/><div className="woven-band band-one"/><div className="woven-band band-two"/><div className="woven-band band-three"/><div className="art-label"><span lang="bn">তামাই</span><span>{t.motif}</span></div></div></div><figcaption><span className="small-diamond" aria-hidden="true">✳</span>{t.motifCaption}</figcaption></figure>
    </section>
    <div className="values-strip"><div className="container">{t.strip.map((text, i) => <span key={text}><span aria-hidden="true">{["✳", "▥", "◇"][i]}</span>{text}</span>)}</div></div>
    <section className="container section about" aria-labelledby="about-title"><div><p className="eyebrow">{t.aboutLabel}</p><h2 id="about-title">{t.aboutTitle}</h2></div><div className="about-copy"><p>{t.about}</p><p>{t.aboutMore}</p></div></section>
    <section className="archive-section section" id="explore"><div className="container"><SectionHeading eyebrow={t.exploreLabel} title={t.exploreTitle} text={t.exploreText}/><div className="category-grid">{t.categories.map((item, i) => <article id={[0,1,4].includes(i) ? categoryAnchors[i] : undefined} className="category-card" key={item.title}><div className="card-top"><Icon kind={i}/><span className="card-number">{new Intl.NumberFormat(locale, { minimumIntegerDigits: 2 }).format(i + 1)}</span></div><h3>{item.title}</h3><p>{item.description}</p>{[2,3,5].includes(i) ? <a href={`#${categoryAnchors[i]}`} className="card-link" aria-label={item.title}><Arrow /></a> : <span className="collection-status">{t.preparing}</span>}</article>)}</div></div></section>
    <section className="textile-section" id="textile"><div className="container textile-inner"><figure className="textile-figure"><div className="swatch-mat"><div className="plaid-swatch"/></div><figcaption><span>{t.swatch}</span><span>{t.swatchNote}</span></figcaption></figure><div className="textile-copy"><p className="eyebrow">{t.textileLabel}</p><h2>{t.textileTitle}</h2><p>{t.textileText}</p><p>{t.textileMore}</p><a className="text-link" href="#contribute">{t.textileLink}<Arrow /></a></div></div></section>
    <section className="container section institutions" id="institutions"><SectionHeading eyebrow={t.institutionsLabel} title={t.institutionsTitle} text={t.institutionsText}/><div className="institution-grid">{t.institutions.map((name, i) => <article key={name}><Icon kind={[0,3,2,4][i]}/><h3>{name}</h3><p>{t.institutionNote}</p></article>)}</div></section>
    <section className="contribute-section container" id="contribute"><div className="contribute-decoration" aria-hidden="true">✳</div><div><p className="eyebrow">{t.contributeLabel}</p><h2>{t.contributeTitle}</h2><p>{t.contributeText}</p></div><div className="contribute-actions"><ul>{t.contributions.map(item => <li key={item}><span aria-hidden="true">＋</span>{item}</li>)}</ul><a className="button button-green" href="#contribution-info" onClick={() => setContributionOpen(true)}>{t.contributeButton}<Arrow /></a><details id="contribution-info" open={contributionOpen} onToggle={event => setContributionOpen(event.currentTarget.open)}><summary>{t.contributionNote}</summary><p>{t.contributionDetails}</p></details></div></section>
    <section className="container section gallery" id="gallery"><SectionHeading eyebrow={t.galleryLabel} title={t.galleryTitle} text={t.galleryText}/><div className="gallery-grid">{t.gallery.map((name, i) => <figure key={name} className={`gallery-item gallery-item-${i}`}><div className="photo-placeholder"><Icon kind={5}/><span>{t.photoPending}</span></div><figcaption><span>{name}</span><span aria-hidden="true">{new Intl.NumberFormat(locale, { minimumIntegerDigits: 2 }).format(i + 1)}</span></figcaption></figure>)}</div><p className="gallery-note">{t.galleryNote}</p></section>
  </main><footer><div className="container"><div className="footer-main"><div><Wordmark/><p className="footer-tagline">{t.tagline}</p><p>{t.footerNote}</p></div><nav aria-label={t.menu}>{t.nav.slice(1).map((name,i) => <a href={`#${anchors[i+1]}`} key={name}>{name}</a>)}</nav></div><div className="footer-bottom"><span>{t.footerPlace}</span><span>{t.footerEnd}</span><a href="#home">{t.backTop} ↑</a></div></div></footer></>;
}
