"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {browserSupabase} from "@/lib/supabase/client";
import {reviewTransitions,type Contribution,type Media,type ReviewEvent} from "@/types/community";
import {CommunityPage,PrivateMedia} from "./community-shared";
import {useLanguage} from "./language-provider";
export function ReviewPanel({initial,media,contributor,events,reviewerId}:{initial:Contribution;media:Media[];contributor:string;events:ReviewEvent[];reviewerId:string}){
 const{copy}=useLanguage();const t=copy.community;const router=useRouter();const[record,setRecord]=useState(initial);const[action,setAction]=useState("");const[notes,setNotes]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState<"reviewSaved"|"notesRequired"|"error"|null>(null);const transitions=reviewTransitions(record.status);const own=record.user_id===reviewerId;
 return <CommunityPage title={record.title} intro={t.review}><p className="community-status">{t.statuses[record.status]}</p><dl className="public-facts community-review-facts">{[[t.contributor,contributor],[t.type,copy.public.contribution.types[["history","story","institution","photo","textile","culture","correction","other"].indexOf(record.contribution_type)]],[t.period,record.approximate_year],[t.location,record.location_text],[t.source,record.source_information],[t.notes,record.additional_notes],[t.reviewerNotes,record.reviewer_notes]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"—"}</dd></div>)}</dl><p className="community-story-text">{record.description}</p><h2>{t.attachments}</h2><div className="community-review-media">{media.map(m=><div key={m.id}>{m.bucket==="contribution-images"&&<PrivateMedia bucket={m.bucket} path={m.path} label={m.original_name} image/>}<PrivateMedia bucket={m.bucket} path={m.path} label={m.original_name}/></div>)}</div>{own?<p className="public-notice">{t.noSelfReview}</p>:transitions.length>0&&<form className="community-review-form" onSubmit={async e=>{e.preventDefault();if(["needs_changes","rejected"].includes(action)&&!notes.trim()){setMessage("notesRequired");return;}const c=browserSupabase();if(!c)return;setBusy(true);try{const{data,error}=await c.rpc("review_contribution",{p_id:record.id,p_status:action,p_notes:notes}).single();if(error)throw error;setRecord(data);setAction("");setMessage("reviewSaved");router.refresh();}catch{setMessage("error");}finally{setBusy(false);}}}><fieldset disabled={busy}><legend className="sr-only">{t.reviewAction}</legend><label>{t.reviewAction}<select required value={action} onChange={e=>setAction(e.target.value)}><option value="">{t.choose}</option>{transitions.map(s=><option key={s} value={s}>{t.statuses[s]}</option>)}</select></label><label>{t.reviewerNotes}<textarea rows={4} maxLength={4000} required={["needs_changes","rejected"].includes(action)} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button type="submit" className="button button-green">{t.apply}</button></fieldset></form>}{message&&<p role="status" className="public-notice">{t[message]}</p>}<h2>{t.history}</h2>{events.length?<ol className="community-review-events">{events.map(e=><li key={e.id}><p>{t.statuses[e.from_status as keyof typeof t.statuses]} → {t.statuses[e.to_status as keyof typeof t.statuses]}</p><p>{e.notes}</p></li>)}</ol>:<p>{t.noReviews}</p>}<Link href="/admin" className="text-link">{t.queue}</Link></CommunityPage>;
}
